refine

diff --git a/.github/workflows/pr-title-checker.yml b/.github/workflows/pr-title-checker.yml
--- a/.github/workflows/pr-title-checker.yml
+++ b/.github/workflows/pr-title-checker.yml
@@ -9,10 +9,11 @@ on:
       - unlabeled
 
 jobs:
-  check:
+  check_pr_title:
+    name: "Check PR title"
     runs-on: ubuntu-latest
     steps:
-      - name: Check type
+      - name: Check commit type
         run: |
           VALID_COMMIT_TYPES="chore|ci|docs|feat|fix|refactor|test"
           REGEX="^((Merge[ a-z-]* branch.*)|(Revert*)|((${VALID_COMMIT_TYPES})(\(.*\))?!?: .*))"
@@ -22,7 +23,8 @@ jobs:
           echo "Commit Message: ${COMMIT_MESSAGE}"
 
           if ! [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
-            echo "::error title=Commit message is not valid::Valid types are ${VALID_COMMIT_TYPES}"
+            echo "::error title=Commit type::Incorrect type used. Valid types are ${VALID_COMMIT_TYPES}"
+            exit 1
           else
-            echo "::notice title=Valid commit message::All good"
+            echo "::notice title=Commit type::All good"
           fi
